### ISSUE TITLE
errore caricando il foglio di calcolo di test

### ISSUE THREAD

**Issue by marklar79** [giovannibussu/WC2018#1]
caricando la partita 50 ottengo questo stacktrace

Exception in thread "main" java.lang.RuntimeException: Il pareggio non e' ammesso
	at worldcup.core.KnockoutPerformance._compareTo(KnockoutPerformance.java:19)
	at worldcup.core.KnockoutPerformance.compareTo(KnockoutPerformance.java:14)
	at worldcup.core.KnockoutPerformance.compareTo(KnockoutPerformance.java:3)
	at java.util.ComparableTimSort.countRunAndMakeAscending(ComparableTimSort.java:320)
	at java.util.ComparableTimSort.sort(ComparableTimSort.java:188)
	at java.util.Arrays.sort(Arrays.java:1246)
	at java.util.Arrays.sort(Arrays.java:1433)
	at java.util.Arrays$ArrayList.sort(Arrays.java:3895)
	at java.util.Collections.sort(Collections.java:141)
	at worldcup.core.AbstractSubTorneo.getAtPosition(AbstractSubTorneo.java:86)
	at worldcup.core.AbstractSubTorneo.initMatches(AbstractSubTorneo.java:127)
	at worldcup.core.AbstractSubTorneo.play(AbstractSubTorneo.java:77)
	at worldcup.core.Match.tryPlay(Match.java:59)
	at worldcup.core.Match.play(Match.java:53)
	at worldcup.core.Torneo.play(Torneo.java:29)
	at worldcup.core.App.main(App.java:44)

ma il risultato della partita non è un pareggio

**Comment by giovannibussu** [comment]
Risolta dal commit 8106f75
